CREATE TABLE Melnikova.SESSIONS(
    SESSIONS_ID INTEGER NOT NULL,
    USER_ID INTEGER NOT NULL,
    BEGIN_DTTM TIMESTAMP,
    END_DTTM TIMESTAMP,
    PRIMARY KEY (SESSIONS_ID),
    FOREIGN KEY (USER_ID) REFERENCES Melnikova.USER(USER_ID)
);

CREATE TABLE Melnikova.PAYMENTS(
    PAYMENT_ID INTEGER NOT NULL,
    USER_ID INTEGER NOT NULL,
    PAYMENT_SUM DOUBLE PRECISION,
    PAYMENT_DTTM TIMESTAMP,
    PRIMARY KEY(PAYMENT_ID),
    FOREIGN KEY (USER_ID) REFERENCES Melnikova.USER(USER_ID)
);

LOAD DATA INFILE '/var/lib/mysql-files/payments.csv' INTO TABLE Melnikova.PAYMENTS
FIELDS TERMINATED BY ';' LINES TERMINATED BY '\n';

LOAD DATA INFILE '/var/lib/mysql-files/sessions.csv' INTO TABLE Melnikova.SESSIONS
FIELDS TERMINATED BY ';' LINES TERMINATED BY '\n';
