CREATE TABLE PAYMENTS(
    PAYMENT_ID INTEGER NOT NULL,
    USER_ID INTEGER NOT NULL,
    PAYMENT_SUM DOUBLE PRECISION,
    PAYMENT_DTTM TIMESTAMP,
    PRIMARY KEY(PAYMENT_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);
