CREATE TABLE SESSIONS(
    SESSIONS_ID INTEGER NOT NULL,
    USER_ID INTEGER NOT NULL,
    BEGIN_DTTM TIMESTAMP,
    END_DTTM TIMESTAMP,
    PRIMARY KEY (SESSIONS_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);