#LOAD DATA INFILE '/var/lib/mysql-files/users.csv' INTO TABLE USERS
#FIELDS TERMINATED BY ';' LINES TERMINATED BY '\n';

LOAD DATA INFILE '/var/lib/mysql-files/payments.csv' INTO TABLE PAYMENTS
FIELDS TERMINATED BY ';' LINES TERMINATED BY '\n';

LOAD DATA INFILE '/var/lib/mysql-files/sessions.csv' INTO TABLE SESSIONS
FIELDS TERMINATED BY ';' LINES TERMINATED BY '\n';