CREATE SCHEMA Melnikova;

CREATE TABLE Melnikova.TRACK(
    TRACK_ID INTEGER NOT NULL,
    RECORDING_PATH VARCHAR(128) NOT NULL,
    GENRE VARCHAR(64),
    TITLE VARCHAR(128),
    DURATION TIME,
    COMMENT VARCHAR(256),
    PRIMARY KEY (TRACK_ID)
);

CREATE TABLE Melnikova.ALBUM(
    ALBUM_ID INTEGER NOT NULL,
    TITLE VARCHAR(128),
    YEAR DATE,
    DESCRIPTION VARCHAR(256),
    PRIMARY KEY (ALBUM_ID)
);

CREATE TABLE Melnikova.ALBUM_X_TRACK(
    ALBUM_ID INTEGER NOT NULL,
    TRACK_ID INTEGER NOT NULL,
    PRIMARY KEY (ALBUM_ID, TRACK_ID),
    FOREIGN KEY (ALBUM_ID) REFERENCES Melnikova.ALBUM(ALBUM_ID),
    FOREIGN KEY (TRACK_ID) REFERENCES Melnikova.TRACK(TRACK_ID)
);

CREATE TABLE Melnikova.ARTIST(
    ARTIST_ID INTEGER NOT NULL,
    SHORT_NAME VARCHAR(128),
    FIRST_NAME VARCHAR(128),
    LAST_NAME VARCHAR(128),
    GENDER VARCHAR(1),
    PRIMARY KEY (ARTIST_ID)
);

CREATE TABLE Melnikova.ARTIST_X_ALBUM(
    ARTIST_ID INTEGER NOT NULL,
    ALBUM_ID INTEGER NOT NULL,
    PRIMARY KEY (ARTIST_ID, ALBUM_ID),
    FOREIGN KEY (ARTIST_ID) REFERENCES Melnikova.ARTIST(ARTIST_ID),
    FOREIGN KEY (ALBUM_ID) REFERENCES Melnikova.ALBUM(ALBUM_ID)
);

CREATE TABLE Melnikova.TRACK_X_ARTIST(
    TRACK_ID INTEGER NOT NULL,
    ARTIST_ID INTEGER NOT NULL,
    PRIMARY KEY (TRACK_ID, ARTIST_ID),
    FOREIGN KEY (ARTIST_ID) REFERENCES Melnikova.ARTIST(ARTIST_ID),
    FOREIGN KEY (TRACK_ID) REFERENCES Melnikova.TRACK(TRACK_ID)
);

CREATE TABLE Melnikova.USER(
    USER_ID INTEGER NOT NULL,
    NAME VARCHAR(128),
    PRIMARY KEY (USER_ID)
);

CREATE TABLE Melnikova.USER_X_TRACK(
    USER_ID INTEGER NOT NULL,
    TRACK_ID INTEGER NOT NULL,
    NUMBER_OG_LISTENING INTEGER,
    ASSESSMENT BOOLEAN,
    ADDED BOOLEAN,
    PRIMARY KEY (USER_ID, TRACK_ID),
    FOREIGN KEY (USER_ID) REFERENCES Melnikova.USER(USER_ID),
    FOREIGN KEY (TRACK_ID) REFERENCES Melnikova.TRACK(TRACK_ID)
);

CREATE TABLE Melnikova.PLAYLIST(
    PLAYLIST_ID INTEGER NOT NULL,
    TITLE VARCHAR(128),
    DESCRIPTION VARCHAR(256),
    PRIMARY KEY (PLAYLIST_ID)
);

CREATE TABLE Melnikova.USER_X_PLAYLIST(
    USER_ID INTEGER NOT NULL,
    PLAYLIST_ID INTEGER NOT NULL,
    PRIMARY KEY (USER_ID, PLAYLIST_ID),
    FOREIGN KEY (USER_ID) REFERENCES Melnikova.USER(USER_ID),
    FOREIGN KEY (PLAYLIST_ID) REFERENCES Melnikova.PLAYLIST(PLAYLIST_ID)
);

CREATE TABLE Melnikova.PLAYLIST_X_TRACK(
    PLAYLIST_ID INTEGER NOT NULL,
    TRACK_ID INTEGER NOT NULL,
    PRIMARY KEY (PLAYLIST_ID, TRACK_ID),
    FOREIGN KEY (TRACK_ID) REFERENCES Melnikova.TRACK(TRACK_ID),
    FOREIGN KEY (PLAYLIST_ID) REFERENCES Melnikova.PLAYLIST(PLAYLIST_ID)
);